### ISSUE TITLE
Client crash on trying to spawning in a multiplayer game

### ISSUE THREAD

**Issue by viktor-ferenczi** [BDCarrillo/RespawnNoPreviewPlugin#1]
Game version: 1.205.023
Plugin version: `8cb378537492e07abed0504b7a8dd446100d9628`

Client side traceback:
```
2024-10-15 01:47:55.611 - Thread:   1 ->  var exception = System.Reflection.TargetParameterCountException: Parameter count mismatch.
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at RespawnMenuNoPreview.Patches.Patch_MyGuiScreenMedicals_ShowPreview.Prefix(MyGuiScreenMedicals __instance, Boolean& ___m_isMultiplayerReady, Object ___m_selectedRowData, Boolean& ___m_selectedRowIsStreamable, Int64& ___m_lastMedicalRoomId, Int32& ___m_showPreviewTime)
   at SpaceEngineers.Game.GUI.MyGuiScreenMedicals.ShowPreview_Patch1(MyGuiScreenMedicals this)
   at SpaceEngineers.Game.GUI.MyGuiScreenMedicals.Update(Boolean hasFocus)
   at Sandbox.Graphics.GUI.MyScreenManager.Update(Int32 totalTimeInMS)
   at Sandbox.Graphics.GUI.MyDX9Gui.Update(Int32 totalTimeInMS)
   at Sandbox.Graphics.GUI.MyGuiSandbox.Update(Int32 totalTimeInMS)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
   at avaness.SpaceEngineersLauncher.Program.StartSpaceEngineers(String[] args)
   at avaness.SpaceEngineersLauncher.Program.Main(String[] args)
```

No error on the server, other than the sudden disconnect.

**Comment by BDCarrillo** [comment]
Resolved and PR in for update, much appreciated!
